// ── OpenCode Plugin Template ────────────────────────────────────────────
//
// String template for the vault0 OpenCode plugin file.
// Generated by `vault0 configure opencode` into ~/.config/opencode/plugins/vault0.ts

/**
 * The plugin template as a TypeScript source string.
 * Placeholder: none — the plugin discovers its config at runtime
 * via `vault0 integration get`.
 *
 * @deprecated Use generatePluginContent() from configure-opencode.ts instead.
 * This template is kept for backward compatibility but is no longer the
 * primary source of truth.
 */
export const OPENCODE_PLUGIN_TEMPLATE = `\
/**
 * Vault0 OpenCode Plugin
 *
 * Detects the active agent, queries vault0 for agent-specific instruction
 * blocks, fetches content via the vault0 CLI, and injects them into the
 * agent's system prompt.
 */

interface IntegrationGetResult {
  instructions: string[]
}

async function fetchAgentInstructions(agentName: string): Promise<string[]> {
  try {
    const proc = Bun.spawn(
      ["vault0", "integration", "get", "--integration=opencode", \\\`--agent=\\\${agentName}\\\`],
      { stdout: "pipe", stderr: "pipe" },
    )
    const text = await new Response(proc.stdout).text()
    const code = await proc.exited
    if (code !== 0) return []
    const result: IntegrationGetResult = JSON.parse(text)
    return result.instructions ?? []
  } catch {
    return []
  }
}

async function fetchInstructionContent(
  client: any,
  name: string,
): Promise<string> {
  try {
    const proc = Bun.spawn(
      ["vault0", "integration", "get", "--integration=opencode", \\\`--block=\\\${name}\\\`],
      { stdout: "pipe", stderr: "pipe" },
    )
    const text = await new Response(proc.stdout).text()
    const code = await proc.exited
    if (code !== 0) {
      await client.app.log({
        body: {
          service: "vault0-plugin",
          level: "warn",
          message: \\\`Failed to fetch block "\\\${name}": exit code \\\${code}\\\`,
        },
      })
      return ""
    }
    return text.trim()
  } catch (err) {
    await client.app.log({
      body: {
        service: "vault0-plugin",
        level: "warn",
        message: \\\`Error fetching block "\\\${name}": \\\${err instanceof Error ? err.message : String(err)}\\\`,
      },
    })
    return ""
  }
}

export const Vault0Plugin = async ({ client }: any) => {
  await client.app.log({
    body: {
      service: "vault0-plugin",
      level: "info",
      message: "Plugin initialized",
    },
  })
  
  return {
    event: async ({ event }: any) => {
      if (event.type !== "session.created") return
      
      const agentName = event.agent?.name
      if (!agentName) return

      const blockNames = await fetchAgentInstructions(agentName)
      if (blockNames.length === 0) return

      const contents = await Promise.all(
        blockNames.map((name) => fetchInstructionContent(client, name)),
      )

      const combined = contents.filter(Boolean).join("\\n\\n")
      if (combined) {
        await client.app.log({
          body: {
            service: "vault0-plugin",
            level: "info",
            message: \\\`Injecting \\\${combined.length} chars of instructions\\\`,
          },
        })
        event.systemPrompt = [event.systemPrompt, combined]
          .filter(Boolean)
          .join("\\n\\n")
      }
    },
  }
}
`
